pull_request_rules:                                                                                                                                                                                          
  - name: fork-pr-exec-test                      
    conditions:                                                                                                                                                                                              
      - "-closed"                 
    actions:                                                                                                                                                                                                 
      label:                     
        add:                                                                                                                                                                                                 
          - "FORK-PR-EXEC-CONFIRMED-2026"
